//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NetworkModel", "FK_Customer_Area", "Area", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FFModal.Area), "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FFModal.Customer), true)]
[assembly: EdmRelationshipAttribute("NetworkModel", "FK_Customer_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FFModal.User), "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FFModal.Customer), true)]
[assembly: EdmRelationshipAttribute("NetworkModel", "FK_CustomerComission_CustomerComission", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FFModal.Customer), "CustomerComission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FFModal.CustomerComission), true)]
[assembly: EdmRelationshipAttribute("NetworkModel", "FK_CustomerComission_Order", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FFModal.Customer), "CustomerComission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FFModal.CustomerComission), true)]
[assembly: EdmRelationshipAttribute("NetworkModel", "FK_Order_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FFModal.Customer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FFModal.Order), true)]

#endregion

namespace FFModal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NetworkEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NetworkEntities object using the connection string found in the 'NetworkEntities' section of the application configuration file.
        /// </summary>
        public NetworkEntities() : base("name=NetworkEntities", "NetworkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NetworkEntities object.
        /// </summary>
        public NetworkEntities(string connectionString) : base(connectionString, "NetworkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NetworkEntities object.
        /// </summary>
        public NetworkEntities(EntityConnection connection) : base(connection, "NetworkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Area> Areas
        {
            get
            {
                if ((_Areas == null))
                {
                    _Areas = base.CreateObjectSet<Area>("Areas");
                }
                return _Areas;
            }
        }
        private ObjectSet<Area> _Areas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bonu> Bonus
        {
            get
            {
                if ((_Bonus == null))
                {
                    _Bonus = base.CreateObjectSet<Bonu>("Bonus");
                }
                return _Bonus;
            }
        }
        private ObjectSet<Bonu> _Bonus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ComissionSetting> ComissionSettings
        {
            get
            {
                if ((_ComissionSettings == null))
                {
                    _ComissionSettings = base.CreateObjectSet<ComissionSetting>("ComissionSettings");
                }
                return _ComissionSettings;
            }
        }
        private ObjectSet<ComissionSetting> _ComissionSettings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerComission> CustomerComissions
        {
            get
            {
                if ((_CustomerComissions == null))
                {
                    _CustomerComissions = base.CreateObjectSet<CustomerComission>("CustomerComissions");
                }
                return _CustomerComissions;
            }
        }
        private ObjectSet<CustomerComission> _CustomerComissions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TaxSetting> TaxSettings
        {
            get
            {
                if ((_TaxSettings == null))
                {
                    _TaxSettings = base.CreateObjectSet<TaxSetting>("TaxSettings");
                }
                return _TaxSettings;
            }
        }
        private ObjectSet<TaxSetting> _TaxSettings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Areas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAreas(Area area)
        {
            base.AddObject("Areas", area);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bonus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBonus(Bonu bonu)
        {
            base.AddObject("Bonus", bonu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ComissionSettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComissionSettings(ComissionSetting comissionSetting)
        {
            base.AddObject("ComissionSettings", comissionSetting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerComissions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerComissions(CustomerComission customerComission)
        {
            base.AddObject("CustomerComissions", customerComission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TaxSettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaxSettings(TaxSetting taxSetting)
        {
            base.AddObject("TaxSettings", taxSetting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetworkModel", Name="Area")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Area : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Area object.
        /// </summary>
        /// <param name="areaCode">Initial value of the AreaCode property.</param>
        public static Area CreateArea(global::System.String areaCode)
        {
            Area area = new Area();
            area.AreaCode = areaCode;
            return area;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AreaCode
        {
            get
            {
                return _AreaCode;
            }
            set
            {
                if (_AreaCode != value)
                {
                    OnAreaCodeChanging(value);
                    ReportPropertyChanging("AreaCode");
                    _AreaCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AreaCode");
                    OnAreaCodeChanged();
                }
            }
        }
        private global::System.String _AreaCode;
        partial void OnAreaCodeChanging(global::System.String value);
        partial void OnAreaCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AreaDescription
        {
            get
            {
                return _AreaDescription;
            }
            set
            {
                OnAreaDescriptionChanging(value);
                ReportPropertyChanging("AreaDescription");
                _AreaDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AreaDescription");
                OnAreaDescriptionChanged();
            }
        }
        private global::System.String _AreaDescription;
        partial void OnAreaDescriptionChanging(global::System.String value);
        partial void OnAreaDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_Customer_Area", "Customer")]
        public EntityCollection<Customer> Customers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Customer>("NetworkModel.FK_Customer_Area", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Customer>("NetworkModel.FK_Customer_Area", "Customer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetworkModel", Name="Bonu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bonu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bonu object.
        /// </summary>
        /// <param name="bonousPaidID">Initial value of the BonousPaidID property.</param>
        /// <param name="bonousPaidDate">Initial value of the BonousPaidDate property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="taxAmount">Initial value of the TaxAmount property.</param>
        /// <param name="netAmountPaid">Initial value of the NetAmountPaid property.</param>
        public static Bonu CreateBonu(global::System.Int32 bonousPaidID, global::System.DateTime bonousPaidDate, global::System.Decimal amount, global::System.Decimal taxAmount, global::System.Decimal netAmountPaid)
        {
            Bonu bonu = new Bonu();
            bonu.BonousPaidID = bonousPaidID;
            bonu.BonousPaidDate = bonousPaidDate;
            bonu.Amount = amount;
            bonu.TaxAmount = taxAmount;
            bonu.NetAmountPaid = netAmountPaid;
            return bonu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BonousPaidID
        {
            get
            {
                return _BonousPaidID;
            }
            set
            {
                if (_BonousPaidID != value)
                {
                    OnBonousPaidIDChanging(value);
                    ReportPropertyChanging("BonousPaidID");
                    _BonousPaidID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BonousPaidID");
                    OnBonousPaidIDChanged();
                }
            }
        }
        private global::System.Int32 _BonousPaidID;
        partial void OnBonousPaidIDChanging(global::System.Int32 value);
        partial void OnBonousPaidIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BonousPaidDate
        {
            get
            {
                return _BonousPaidDate;
            }
            set
            {
                OnBonousPaidDateChanging(value);
                ReportPropertyChanging("BonousPaidDate");
                _BonousPaidDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BonousPaidDate");
                OnBonousPaidDateChanged();
            }
        }
        private global::System.DateTime _BonousPaidDate;
        partial void OnBonousPaidDateChanging(global::System.DateTime value);
        partial void OnBonousPaidDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TaxAmount
        {
            get
            {
                return _TaxAmount;
            }
            set
            {
                OnTaxAmountChanging(value);
                ReportPropertyChanging("TaxAmount");
                _TaxAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxAmount");
                OnTaxAmountChanged();
            }
        }
        private global::System.Decimal _TaxAmount;
        partial void OnTaxAmountChanging(global::System.Decimal value);
        partial void OnTaxAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NetAmountPaid
        {
            get
            {
                return _NetAmountPaid;
            }
            set
            {
                OnNetAmountPaidChanging(value);
                ReportPropertyChanging("NetAmountPaid");
                _NetAmountPaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NetAmountPaid");
                OnNetAmountPaidChanged();
            }
        }
        private global::System.Decimal _NetAmountPaid;
        partial void OnNetAmountPaidChanging(global::System.Decimal value);
        partial void OnNetAmountPaidChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetworkModel", Name="ComissionSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ComissionSetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ComissionSetting object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="maxLevel">Initial value of the MaxLevel property.</param>
        /// <param name="maxNode">Initial value of the MaxNode property.</param>
        /// <param name="comissionPercentage">Initial value of the ComissionPercentage property.</param>
        public static ComissionSetting CreateComissionSetting(global::System.Int32 id, global::System.Int32 maxLevel, global::System.Int32 maxNode, global::System.Decimal comissionPercentage)
        {
            ComissionSetting comissionSetting = new ComissionSetting();
            comissionSetting.ID = id;
            comissionSetting.MaxLevel = maxLevel;
            comissionSetting.MaxNode = maxNode;
            comissionSetting.ComissionPercentage = comissionPercentage;
            return comissionSetting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxLevel
        {
            get
            {
                return _MaxLevel;
            }
            set
            {
                OnMaxLevelChanging(value);
                ReportPropertyChanging("MaxLevel");
                _MaxLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxLevel");
                OnMaxLevelChanged();
            }
        }
        private global::System.Int32 _MaxLevel;
        partial void OnMaxLevelChanging(global::System.Int32 value);
        partial void OnMaxLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxNode
        {
            get
            {
                return _MaxNode;
            }
            set
            {
                OnMaxNodeChanging(value);
                ReportPropertyChanging("MaxNode");
                _MaxNode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxNode");
                OnMaxNodeChanged();
            }
        }
        private global::System.Int32 _MaxNode;
        partial void OnMaxNodeChanging(global::System.Int32 value);
        partial void OnMaxNodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ComissionPercentage
        {
            get
            {
                return _ComissionPercentage;
            }
            set
            {
                OnComissionPercentageChanging(value);
                ReportPropertyChanging("ComissionPercentage");
                _ComissionPercentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComissionPercentage");
                OnComissionPercentageChanged();
            }
        }
        private global::System.Decimal _ComissionPercentage;
        partial void OnComissionPercentageChanging(global::System.Decimal value);
        partial void OnComissionPercentageChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetworkModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="membershipID">Initial value of the MembershipID property.</param>
        /// <param name="introducerID">Initial value of the IntroducerID property.</param>
        /// <param name="referenceID">Initial value of the ReferenceID property.</param>
        /// <param name="customerName">Initial value of the CustomerName property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="nationality">Initial value of the Nationality property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="municipality">Initial value of the Municipality property.</param>
        /// <param name="district">Initial value of the District property.</param>
        /// <param name="street">Initial value of the Street property.</param>
        /// <param name="areaCode">Initial value of the AreaCode property.</param>
        /// <param name="homeNumber">Initial value of the HomeNumber property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static Customer CreateCustomer(global::System.String membershipID, global::System.String introducerID, global::System.String referenceID, global::System.String customerName, global::System.String gender, global::System.DateTime dateOfBirth, global::System.DateTime createdDate, global::System.Int32 createdBy, global::System.String nationality, global::System.String country, global::System.String city, global::System.String municipality, global::System.String district, global::System.String street, global::System.String areaCode, global::System.String homeNumber, global::System.String address)
        {
            Customer customer = new Customer();
            customer.MembershipID = membershipID;
            customer.IntroducerID = introducerID;
            customer.ReferenceID = referenceID;
            customer.CustomerName = customerName;
            customer.Gender = gender;
            customer.DateOfBirth = dateOfBirth;
            customer.CreatedDate = createdDate;
            customer.CreatedBy = createdBy;
            customer.Nationality = nationality;
            customer.Country = country;
            customer.City = city;
            customer.Municipality = municipality;
            customer.District = district;
            customer.Street = street;
            customer.AreaCode = areaCode;
            customer.HomeNumber = homeNumber;
            customer.Address = address;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MembershipID
        {
            get
            {
                return _MembershipID;
            }
            set
            {
                if (_MembershipID != value)
                {
                    OnMembershipIDChanging(value);
                    ReportPropertyChanging("MembershipID");
                    _MembershipID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MembershipID");
                    OnMembershipIDChanged();
                }
            }
        }
        private global::System.String _MembershipID;
        partial void OnMembershipIDChanging(global::System.String value);
        partial void OnMembershipIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IntroducerID
        {
            get
            {
                return _IntroducerID;
            }
            set
            {
                OnIntroducerIDChanging(value);
                ReportPropertyChanging("IntroducerID");
                _IntroducerID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IntroducerID");
                OnIntroducerIDChanged();
            }
        }
        private global::System.String _IntroducerID;
        partial void OnIntroducerIDChanging(global::System.String value);
        partial void OnIntroducerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReferenceID
        {
            get
            {
                return _ReferenceID;
            }
            set
            {
                OnReferenceIDChanging(value);
                ReportPropertyChanging("ReferenceID");
                _ReferenceID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReferenceID");
                OnReferenceIDChanged();
            }
        }
        private global::System.String _ReferenceID;
        partial void OnReferenceIDChanging(global::System.String value);
        partial void OnReferenceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BenificiaryName
        {
            get
            {
                return _BenificiaryName;
            }
            set
            {
                OnBenificiaryNameChanging(value);
                ReportPropertyChanging("BenificiaryName");
                _BenificiaryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BenificiaryName");
                OnBenificiaryNameChanged();
            }
        }
        private global::System.String _BenificiaryName;
        partial void OnBenificiaryNameChanging(global::System.String value);
        partial void OnBenificiaryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.Int32 _CreatedBy;
        partial void OnCreatedByChanging(global::System.Int32 value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaratialStatus
        {
            get
            {
                return _MaratialStatus;
            }
            set
            {
                OnMaratialStatusChanging(value);
                ReportPropertyChanging("MaratialStatus");
                _MaratialStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaratialStatus");
                OnMaratialStatusChanged();
            }
        }
        private global::System.String _MaratialStatus;
        partial void OnMaratialStatusChanging(global::System.String value);
        partial void OnMaratialStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CitizenshipID
        {
            get
            {
                return _CitizenshipID;
            }
            set
            {
                OnCitizenshipIDChanging(value);
                ReportPropertyChanging("CitizenshipID");
                _CitizenshipID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CitizenshipID");
                OnCitizenshipIDChanged();
            }
        }
        private global::System.String _CitizenshipID;
        partial void OnCitizenshipIDChanging(global::System.String value);
        partial void OnCitizenshipIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LicenseID
        {
            get
            {
                return _LicenseID;
            }
            set
            {
                OnLicenseIDChanging(value);
                ReportPropertyChanging("LicenseID");
                _LicenseID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LicenseID");
                OnLicenseIDChanged();
            }
        }
        private global::System.String _LicenseID;
        partial void OnLicenseIDChanging(global::System.String value);
        partial void OnLicenseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassportID
        {
            get
            {
                return _PassportID;
            }
            set
            {
                OnPassportIDChanging(value);
                ReportPropertyChanging("PassportID");
                _PassportID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PassportID");
                OnPassportIDChanged();
            }
        }
        private global::System.String _PassportID;
        partial void OnPassportIDChanging(global::System.String value);
        partial void OnPassportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Municipality
        {
            get
            {
                return _Municipality;
            }
            set
            {
                OnMunicipalityChanging(value);
                ReportPropertyChanging("Municipality");
                _Municipality = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Municipality");
                OnMunicipalityChanged();
            }
        }
        private global::System.String _Municipality;
        partial void OnMunicipalityChanging(global::System.String value);
        partial void OnMunicipalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String District
        {
            get
            {
                return _District;
            }
            set
            {
                OnDistrictChanging(value);
                ReportPropertyChanging("District");
                _District = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("District");
                OnDistrictChanged();
            }
        }
        private global::System.String _District;
        partial void OnDistrictChanging(global::System.String value);
        partial void OnDistrictChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AreaCode
        {
            get
            {
                return _AreaCode;
            }
            set
            {
                OnAreaCodeChanging(value);
                ReportPropertyChanging("AreaCode");
                _AreaCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AreaCode");
                OnAreaCodeChanged();
            }
        }
        private global::System.String _AreaCode;
        partial void OnAreaCodeChanging(global::System.String value);
        partial void OnAreaCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HomeNumber
        {
            get
            {
                return _HomeNumber;
            }
            set
            {
                OnHomeNumberChanging(value);
                ReportPropertyChanging("HomeNumber");
                _HomeNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HomeNumber");
                OnHomeNumberChanged();
            }
        }
        private global::System.String _HomeNumber;
        partial void OnHomeNumberChanging(global::System.String value);
        partial void OnHomeNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeTelephone
        {
            get
            {
                return _HomeTelephone;
            }
            set
            {
                OnHomeTelephoneChanging(value);
                ReportPropertyChanging("HomeTelephone");
                _HomeTelephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeTelephone");
                OnHomeTelephoneChanged();
            }
        }
        private global::System.String _HomeTelephone;
        partial void OnHomeTelephoneChanging(global::System.String value);
        partial void OnHomeTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_Customer_Area", "Area")]
        public Area Area
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("NetworkModel.FK_Customer_Area", "Area").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("NetworkModel.FK_Customer_Area", "Area").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Area> AreaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("NetworkModel.FK_Customer_Area", "Area");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Area>("NetworkModel.FK_Customer_Area", "Area", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_Customer_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("NetworkModel.FK_Customer_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("NetworkModel.FK_Customer_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("NetworkModel.FK_Customer_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("NetworkModel.FK_Customer_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_CustomerComission_CustomerComission", "CustomerComission")]
        public EntityCollection<CustomerComission> CustomerComissions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerComission>("NetworkModel.FK_CustomerComission_CustomerComission", "CustomerComission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerComission>("NetworkModel.FK_CustomerComission_CustomerComission", "CustomerComission", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_CustomerComission_Order", "CustomerComission")]
        public EntityCollection<CustomerComission> CustomerComissions1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerComission>("NetworkModel.FK_CustomerComission_Order", "CustomerComission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerComission>("NetworkModel.FK_CustomerComission_Order", "CustomerComission", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_Order_Customer", "Order")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("NetworkModel.FK_Order_Customer", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("NetworkModel.FK_Order_Customer", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetworkModel", Name="CustomerComission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerComission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerComission object.
        /// </summary>
        /// <param name="comissionID">Initial value of the ComissionID property.</param>
        /// <param name="membershipID">Initial value of the MembershipID property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="comissionPaidDate">Initial value of the ComissionPaidDate property.</param>
        /// <param name="isComissionPaid">Initial value of the IsComissionPaid property.</param>
        public static CustomerComission CreateCustomerComission(global::System.Int32 comissionID, global::System.String membershipID, global::System.Int32 orderID, global::System.Decimal amount, global::System.DateTime comissionPaidDate, global::System.Boolean isComissionPaid)
        {
            CustomerComission customerComission = new CustomerComission();
            customerComission.ComissionID = comissionID;
            customerComission.MembershipID = membershipID;
            customerComission.OrderID = orderID;
            customerComission.Amount = amount;
            customerComission.ComissionPaidDate = comissionPaidDate;
            customerComission.IsComissionPaid = isComissionPaid;
            return customerComission;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComissionID
        {
            get
            {
                return _ComissionID;
            }
            set
            {
                if (_ComissionID != value)
                {
                    OnComissionIDChanging(value);
                    ReportPropertyChanging("ComissionID");
                    _ComissionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ComissionID");
                    OnComissionIDChanged();
                }
            }
        }
        private global::System.Int32 _ComissionID;
        partial void OnComissionIDChanging(global::System.Int32 value);
        partial void OnComissionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MembershipID
        {
            get
            {
                return _MembershipID;
            }
            set
            {
                OnMembershipIDChanging(value);
                ReportPropertyChanging("MembershipID");
                _MembershipID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MembershipID");
                OnMembershipIDChanged();
            }
        }
        private global::System.String _MembershipID;
        partial void OnMembershipIDChanging(global::System.String value);
        partial void OnMembershipIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                OnOrderIDChanging(value);
                ReportPropertyChanging("OrderID");
                _OrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderID");
                OnOrderIDChanged();
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ComissionPaidDate
        {
            get
            {
                return _ComissionPaidDate;
            }
            set
            {
                OnComissionPaidDateChanging(value);
                ReportPropertyChanging("ComissionPaidDate");
                _ComissionPaidDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComissionPaidDate");
                OnComissionPaidDateChanged();
            }
        }
        private global::System.DateTime _ComissionPaidDate;
        partial void OnComissionPaidDateChanging(global::System.DateTime value);
        partial void OnComissionPaidDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsComissionPaid
        {
            get
            {
                return _IsComissionPaid;
            }
            set
            {
                OnIsComissionPaidChanging(value);
                ReportPropertyChanging("IsComissionPaid");
                _IsComissionPaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsComissionPaid");
                OnIsComissionPaidChanged();
            }
        }
        private global::System.Boolean _IsComissionPaid;
        partial void OnIsComissionPaidChanging(global::System.Boolean value);
        partial void OnIsComissionPaidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_CustomerComission_CustomerComission", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_CustomerComission_CustomerComission", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_CustomerComission_CustomerComission", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_CustomerComission_CustomerComission", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("NetworkModel.FK_CustomerComission_CustomerComission", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_CustomerComission_Order", "Customer")]
        public Customer Customer1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_CustomerComission_Order", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_CustomerComission_Order", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> Customer1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_CustomerComission_Order", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("NetworkModel.FK_CustomerComission_Order", "Customer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetworkModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="membershipID">Initial value of the MembershipID property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="isDelivered">Initial value of the IsDelivered property.</param>
        /// <param name="deliveredDate">Initial value of the DeliveredDate property.</param>
        public static Order CreateOrder(global::System.Int32 orderID, global::System.String membershipID, global::System.String description, global::System.Decimal amount, global::System.Boolean isDelivered, global::System.DateTime deliveredDate)
        {
            Order order = new Order();
            order.OrderID = orderID;
            order.MembershipID = membershipID;
            order.Description = description;
            order.Amount = amount;
            order.IsDelivered = isDelivered;
            order.DeliveredDate = deliveredDate;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MembershipID
        {
            get
            {
                return _MembershipID;
            }
            set
            {
                OnMembershipIDChanging(value);
                ReportPropertyChanging("MembershipID");
                _MembershipID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MembershipID");
                OnMembershipIDChanged();
            }
        }
        private global::System.String _MembershipID;
        partial void OnMembershipIDChanging(global::System.String value);
        partial void OnMembershipIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDelivered
        {
            get
            {
                return _IsDelivered;
            }
            set
            {
                OnIsDeliveredChanging(value);
                ReportPropertyChanging("IsDelivered");
                _IsDelivered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDelivered");
                OnIsDeliveredChanged();
            }
        }
        private global::System.Boolean _IsDelivered;
        partial void OnIsDeliveredChanging(global::System.Boolean value);
        partial void OnIsDeliveredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DeliveredDate
        {
            get
            {
                return _DeliveredDate;
            }
            set
            {
                OnDeliveredDateChanging(value);
                ReportPropertyChanging("DeliveredDate");
                _DeliveredDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveredDate");
                OnDeliveredDateChanged();
            }
        }
        private global::System.DateTime _DeliveredDate;
        partial void OnDeliveredDateChanging(global::System.DateTime value);
        partial void OnDeliveredDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_Order_Customer", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_Order_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_Order_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NetworkModel.FK_Order_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("NetworkModel.FK_Order_Customer", "Customer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetworkModel", Name="TaxSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaxSetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TaxSetting object.
        /// </summary>
        /// <param name="taxID">Initial value of the TaxID property.</param>
        /// <param name="taxRate">Initial value of the TaxRate property.</param>
        public static TaxSetting CreateTaxSetting(global::System.Int32 taxID, global::System.Int32 taxRate)
        {
            TaxSetting taxSetting = new TaxSetting();
            taxSetting.TaxID = taxID;
            taxSetting.TaxRate = taxRate;
            return taxSetting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TaxID
        {
            get
            {
                return _TaxID;
            }
            set
            {
                if (_TaxID != value)
                {
                    OnTaxIDChanging(value);
                    ReportPropertyChanging("TaxID");
                    _TaxID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxID");
                    OnTaxIDChanged();
                }
            }
        }
        private global::System.Int32 _TaxID;
        partial void OnTaxIDChanging(global::System.Int32 value);
        partial void OnTaxIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TaxRate
        {
            get
            {
                return _TaxRate;
            }
            set
            {
                OnTaxRateChanging(value);
                ReportPropertyChanging("TaxRate");
                _TaxRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxRate");
                OnTaxRateChanged();
            }
        }
        private global::System.Int32 _TaxRate;
        partial void OnTaxRateChanging(global::System.Int32 value);
        partial void OnTaxRateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetworkModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="role">Initial value of the Role property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="middleName">Initial value of the MiddleName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="designation">Initial value of the Designation property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        public static User CreateUser(global::System.Int32 userID, global::System.String userName, global::System.String password, global::System.String role, global::System.String firstName, global::System.String middleName, global::System.String lastName, global::System.String designation, global::System.DateTime createdDate)
        {
            User user = new User();
            user.UserID = userID;
            user.UserName = userName;
            user.Password = password;
            user.Role = role;
            user.FirstName = firstName;
            user.MiddleName = middleName;
            user.LastName = lastName;
            user.Designation = designation;
            user.CreatedDate = createdDate;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NetworkModel", "FK_Customer_User", "Customer")]
        public EntityCollection<Customer> Customers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Customer>("NetworkModel.FK_Customer_User", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Customer>("NetworkModel.FK_Customer_User", "Customer", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
